CREATE TABLE `channel` (
	`id` INT NOT NULL AUTO_INCREMENT COMMENT '账户的自增id',
	`created_time` TIMESTAMP ( 6 ) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP ( 6 ),
	`updated_time` TIMESTAMP ( 6 ) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP ( 6 ) ON UPDATE CURRENT_TIMESTAMP ( 6 ),
	`deleted_time` TIMESTAMP ( 6 ) NULL COMMENT '删除时间',
`name` VARCHAR ( 64 ) NOT NULL COMMENT '频道名称',
PRIMARY KEY ( `id` )) ENGINE = INNODB;

CREATE TABLE `message` (
	`id` INT NOT NULL AUTO_INCREMENT COMMENT '账户的自增id',
	`created_time` TIMESTAMP ( 6 ) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP ( 6 ),
	`updated_time` TIMESTAMP ( 6 ) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP ( 6 ) ON UPDATE CURRENT_TIMESTAMP ( 6 ),
	`deleted_time` TIMESTAMP ( 6 ) NULL COMMENT '删除时间',
	`title` VARCHAR ( 64 ) NOT NULL COMMENT '标题',
	`content` VARCHAR ( 512 ) NOT NULL COMMENT '内容',
	`channel_id` INT NOT NULL COMMENT '频道id',
INDEX `IDX_f6d0a3bccef803efd6d5102655` ( `channel_id` ),
PRIMARY KEY ( `id` )) ENGINE = INNODB;
